baseURL = 'https://platinumxy.com/'
languageCode = 'en'
theme = 'rusty-typewriter'
title = 'platinumxy'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
tag = 'tags'
topic = 'topics'
series = 'series'

[params.author]
name = 'platinumxy'

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 1

[[menus.main]]
name = 'Search'
pageRef = '/search'
weight = 2

[[menus.main]]
name = 'About'
pageRef = '/about.md'
weight = 3

# ==== Search functions ====
[outputFormats]
 [outputFormats.SearchIndex]
  mediaType = "application/json"
  baseName = "searchindex"
  isPlainText = true
  notAlternative = true

[mediaTypes]
 [mediaTypes."application/json"]
  suffixes = ["json"]

[outputs]
 home = ["HTML","RSS", "SearchIndex"]
# ==========================
